heat_template_version: 2015-04-30
description: Launching instance with floating IP.
parameters:
        name: 
                type: string
                default: private_network
                description: name of the network
        public_network:
                type: string
                label: Public network name or ID
                description: Public network with floating IP addresses.
                default: external_network
resources:
        network_port:
                type: OS::Neutron::Port
                properties:
                        network: { get_param: name }
        instance_input:
                type: OS::Nova::Server
                properties:
                        name: testinstance1
                        networks:
                        - port: {get_resource: network_port}
                        flavor: m1.tiny
                        image: cirros
        floating_ip:
                type: OS::Neutron::FloatingIP
                properties:
                        floating_network: { get_param: public_network }
        floating_ip_assoc:
                type: OS::Neutron::FloatingIPAssociation
                properties:
                        floatingip_id: { get_resource: floating_ip }
                        port_id: { get_resource: network_port }
outputs:
        output_name:
                description: Name of the spawned instance.
                value: {get_attr: [instance_input, name]}
        output_ip:
                description: ip address of the instance
                value: {get_attr: [instance_input, networks]}
